# Generated by Django 4.0.3 on 2022-10-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_alter_salerecord_automobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
