# Generated by Django 4.0.3 on 2022-10-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_automobilevo_is_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecord',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='employee_number',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
