# Generated by Django 4.0.3 on 2022-10-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobilevo',
            options={'verbose_name': 'AutomobileVO', 'verbose_name_plural': 'AutomobileVOs'},
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='vin',
            field=models.CharField(max_length=17),
        ),
    ]
